print("Hello!")
print("Whats your name?")
name = input("?")
print("Hello, ", name)
print ("This is a Mad Libs program. I will ask you for 8 words and put them in a random paragraph")
color = input('Please pick a color')
place = input('Please pick a place')
temp = input('Please pick a temp')
color2 = input('Please pick a color')
verb = input('Please pick a verb')
sport = input('Please pick a sport')
lang = input('Please pick a language')
act = input('Please pick a activity')
print("The sky is ", color, " in ", place, " and its always ", temp, " the lakes are ", color2, " people always ", verb, " around, everyone likes to play ", sport, " everyone speaks ", lang, " everyone likes the activity of ", act, "done")

